### ISSUE TITLE
format bed file

### ISSUE THREAD

**Issue by pierrespc** [DivyaratanPopli/Kinship_Inference#11]
Hi,

I am trying to run KINgaroo. I am wondering if the chr info in bed files need to be only numerical or if they can be of format chr<chr>  like following:

``` more ../example_files/ALT_bedfile.bed 
chr1	839494	839495	G	T
chr1	846863	846864	G	C
chr1	851203	851204	G	C
chr1	853088	853089	G	C
chr1	855074	855075	C	G
chr1	858039	858040	C	A
chr1	867551	867552	T	G
chr1	870738	870739	T	G
chr1	871027	871028	A	C
chr1	897324	897325	G	C
```
because the splitted bed files created are empty and all my alignments and so on are with contig names including chr<chr>.
If it is not contemplated, I suppose I should just change some function in the script ```pypackage/kingaroo/KINgaroo/KINgaroo_scripts/helpers.py ``` but before editing  your script I would rather confirm there is no trick for this case.
Thanks

**Comment by DivyaratanPopli** [comment]
Hi, chr needs to be numeric in bed file as well as bamfiles. Please refer to README.md for information on input files. I think it's easier to change the input files to numeric chr than editing the script because at different places, the script loops through chromosomes as integers.
