### ISSUE TITLE
Paths of bam files

### ISSUE THREAD

**Issue by npsonis** [DivyaratanPopli/Kinship_Inference#12]
Hi, great tool!

I was wondering if it will be better to have as input a list of bam file names with their entire path instead of providing the directory where the bam files are located and a list of their names. In this way someone would not have to cp large BAM files from different directories to a single one. Many pipelines produce the final BAM files in separate directories per sample not all-together in a single directory. 

Also, please add argument for version.

**Comment by DivyaratanPopli** [comment]
Hi, thank you for the nice suggestion, I will change this soon.
