### ISSUE TITLE
KINgaroo freeze

### ISSUE THREAD

**Issue by smoothOperatoor** [DivyaratanPopli/Kinship_Inference#13]
Hi!

I have experienced an issue running KINgaroo. The software starts fine but freezes at the creating input step, as shown below:

Finished indexing, sorting and splitting bamfiles...
Merging all chromosomes..
Creating input files from chromosome 1...
Creating input files from chromosome 2...
Creating input files from chromosome 3...
Creating input files from chromosome 4...
Creating input files from chromosome 5...
Creating input files from chromosome 6...
Creating input files from chromosome 7...
Creating input files from chromosome 8...
Creating input files from chromosome 9...
Creating input files from chromosome 10...
Creating input files from chromosome 11...
Creating input files from chromosome 12...
Creating input files from chromosome 13...
Creating input files from chromosome 14...
Creating input files from chromosome 15...
Creating input files from chromosome 16...
Creating input files from chromosome 17...
Creating input files from chromosome 18...
Creating input files from chromosome 19...
Creating input files from chromosome 20...
Creating input files from chromosome 21...
Creating input files from chromosome 22…

I am using the latest version and I have tested my input files and they seem fine.  The command I use is:

KINgaroo -bam /home/user/BAM/ -bed example_files/snps_KINanalysis.bed -T example_files/targets_KINanalysis.txt -s 0 -cnt 0

Any thoughts on the issue?

Thank you very much in advance!

**Comment by smoothOperatoor** [comment]
A small update:

I managed to get KINgaroo to work by running it outside of conda environment. However, ROHs are not inferred correctly (or at all) as I get this error when running KIN:

FileNotFoundError: /home/user/Desktop/FINAL//likfiles/name1_._name2.csv not found.

**Comment by DivyaratanPopli** [comment]
Hi, looks like KINgaroo, did not make all the required files. Can you check that it finished without errors?

**Comment by SevvalAkturk** [comment]
Hi, I have a similar problem. I checked KINgaroo and it finished without errors (as shown below). However, when I ran KIN, it threw the same error as "_smoothOperator_" reported earlier.

Do you have any suggestions for that? 

Finished merging all chromosomes...
Estimating p_0...
Inferring positions of long ROH in xxx.bam
Inferring positions of long ROH in yyy.bam
Inferring positions of long ROH in zzz.bam
