### ISSUE TITLE
KinGAROO freezes when estimating hapProbs

### ISSUE THREAD

**Issue by pierrespc** [DivyaratanPopli/Kinship_Inference#16]
Hi,

I can't make kingGAROO to finish the hapProbs estimation.
I am running it on 6 test samples. 
the chrm{chr}.bam   and chrm$chr.sorted.bam{,.bai} files has been created by the software.
Then it went to estimate the hapProbs. It was running well as it created the chrm$chr.{diffs,probs} files for 5 samples and the 22  chromosomes. BUT for the last sample in the list it got stucked and did not create theese files for chromosomes 4 and 14.
Note that the program did not exit and is still running but I have no error in stderr and the stdout just gave me "Indexing  <filename_pref>".
Have you notice this behaviour before? What can be done to avoid the software to freeze?

Thanks.

Best

**Comment by DivyaratanPopli** [comment]
Hi, I have not seen this behavior. Can you run the script with 5 samples to see if there is still a problem? Is the 6th file much bigger than the rest (is it shotgun data)? You can check if the program is doing something or is just idle with htop, maybe it just requires more time. If it is shotgun data, you can filter out all the monomorphic sites from the bed file to make things faster.

**Comment by pierrespc** [comment]
Hi,

thanks for your answer. I have run now on 5 samples as you suggest. Note that the bed file I give as input for now as a test is the bed file for the 1240K SNP panel. Also the program was not doing anything and was in the same state all over the weekend.
I'll let you know how it goes with the 5 samples test.
Best

**Comment by pierrespc** [comment]
Ok, it went through the hapProbs process.
I got an error much after ("hbd_hmm_functions.py:355: RuntimeWarning: invalid value encountered in long_scalars
  goodprop=np.sum((harr>=0.7) & (harr<1.1))/np.sum(harr<=1.1)")
 but I guess it is because one genome is at very low coverage. I am now trying with genomas with higher coverage.
Thanks!

**Comment by pierrespc** [comment]
Ok. now it ran OK and i got consistent results from other methods with 5 samples.
Looks like the frozen status issue was because of memory.  Today, I had again the issue as before with samples at higher coverage. And although I didn't get any error, I cancelled the job and submit it with higher memory, and it ran OK.
It is weird that when memory is not sufficient, the process freezes instaed of returning an error.
Now I'll scale up the analyses.
Thanks for your help.
Best
