### ISSUE TITLE
Multiple nodes

### ISSUE THREAD

**Issue by ocdorsey** [DivyaratanPopli/Kinship_Inference#20]
Hi, 

I am processing many samples and wondered whether KINgaroo supports multiple node processing on an HPC.

Thanks!

**Comment by DivyaratanPopli** [comment]
Hi, the current implementation unfortunately does not support multiple node processing. But with around ~100 samples, KINgaroo can finish in a couple of days on a single node machine with ~50 cores. Hope that helps.
