### ISSUE TITLE
[documentation] `samtools` & `bcftools` should explicitely be listed as dependencies.

### ISSUE THREAD

**Issue by MaelLefeuvre** [DivyaratanPopli/Kinship_Inference#7]
Hi, 

First and foremost, thank you for your work on this very promising kinship estimation method, and congratulation on your recently published paper!

I just have a quick suggestion in regards to your documentation, [README](https://github.com/DivyaratanPopli/Kinship_Inference/blob/484e467fcb20d7d6c2f63988570e4f26f5000318/README.md) file, and conda environment definition [here](https://github.com/DivyaratanPopli/Kinship_Inference/blob/484e467fcb20d7d6c2f63988570e4f26f5000318/README.md#conda-environment). Namely, I think you perhaps forgot to explicitely mention `bcftools` and `samtools` as a direct dependency of KINGaroo - since you're running multiple subprocesses of them in [helpers.py](https://github.com/DivyaratanPopli/Kinship_Inference/blob/484e467fcb20d7d6c2f63988570e4f26f5000318/pypackage/kingaroo/KINgaroo/KINgaroo_scripts/helpers.py), if I'm not mistaken.

These softwares do come pre-installed on Ubuntu distrubtions, but may not be available on all UNIX platforms. This may trip up users during their installation process, especially those running your software on HPC environments and/or embedding your software within container infrastructure such as Singularity or Docker.

Maybe providing users with an updated yaml definition file could be of help ? `kin-3.1.3-environment.yml` would thus be something in the likes of:

```
name: kin-3.1.3
channels:
  - conda-forge
  - bioconda 
dependencies:
  - conda-forge::python=3.8
  - conda-forge::scipy=1.8.0
  - conda-forge::numpy=1.21.1
  - conda-forge::pandas=1.3.1
  - conda-forge::numba=0.55.1
  - bioconda::pysam=0.19.0
  - bioconda::pybedtools=0.9.0
  - bioconda::samtools>=1.15
  - bioconda::bcftools>=1.15
```

Anyway, hope this helps, and thanks again for this great contribution !

Cheers

**Comment by DivyaratanPopli** [comment]
Hi, thank you for pointing this out. I have now added the environment file.
Cheers
